// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

/**
 * An enumeration for FRC districts.
 */
export type District =
  | "North Carolina"
  | "Texas"
  | "Indiana"
  | "Mid-Atlantic"
  | "Chesapeake"
  | "Michigan"
  | "South Carolina"
  | "Peachtree"
  | "Pacific Northwest"
  | "Israel"
  | "Ontario"
  | "New England"
  | ""

/**
 * SQL table that holds event specific information from TBA.
 */
export type Event = {
  year: number
  key: string
  name: string
  country: string | null
  state_prov: StateProv
  city: string | null
  district: District
  start_date: string
  end_date: string
  event_type: EventType
  week: number
}

export type EventSearch = {
  name: string
  key: string
}

/**
 * An enumeration for event type.
 *
 * Members:
 * INVALID: The event is invalid for some reason.
 * REGIONAL: The event is a traditional regional event.
 * DISTRICT: The event is a district qualifying event.
 * DISTRICT_CMP: The event is a distict championship event.
 * CMP_DIV: The event is a division at the world championship.
 * EINSTEIN: The event is the Einstein final at world championship.
 * DISTRICT_CMP_DIV: The event is a district championship division.
 * OFFSEASON: The event is an offseason event.
 */
export type EventType = -1 | 0 | 1 | 2 | 3 | 4 | 5 | 99

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

/**
 * SQL table that holds match information from TBA
 */
export type Match = {
  year: number
  event_key: string
  key: string
  match_type: MatchType
  set_number: number
  match_number: number
  status: MatchStatus
  video: string | null
  red_1: string
  red_2: string
  red_3: string | null
  red_dq: string
  red_surrogate: string
  blue_1: string
  blue_2: string
  blue_3: string | null
  blue_dq: string
  blue_surrogate: string
  winner: MatchWinner | null
  time: string | null
  actual_time: string | null
  predicted_time: string | null
  red_score?: number | null
  red_no_foul_points?: number | null
  red_foul_points?: number | null
  red_auto_points?: number | null
  red_teleop_points?: number | null
  red_endgame_points?: number | null
  red_endgame_1?: number | null
  red_endgame_2?: number | null
  red_endgame_3?: number | null
  red_rp_1?: boolean | null
  red_rp_2?: boolean | null
  red_rp_3?: boolean | null
  red_comp_1?: number | null
  red_comp_2?: number | null
  red_comp_3?: number | null
  red_comp_4?: number | null
  red_comp_5?: number | null
  red_comp_6?: number | null
  red_comp_7?: number | null
  red_comp_8?: number | null
  red_comp_9?: number | null
  red_comp_10?: number | null
  red_comp_11?: number | null
  red_comp_12?: number | null
  red_comp_13?: number | null
  red_comp_14?: number | null
  red_comp_15?: number | null
  red_comp_16?: number | null
  red_comp_17?: number | null
  red_comp_18?: number | null
  blue_score?: number | null
  blue_no_foul_points?: number | null
  blue_foul_points?: number | null
  blue_auto_points?: number | null
  blue_teleop_points?: number | null
  blue_endgame_points?: number | null
  blue_endgame_1?: number | null
  blue_endgame_2?: number | null
  blue_endgame_3?: number | null
  blue_rp_1?: boolean | null
  blue_rp_2?: boolean | null
  blue_rp_3?: boolean | null
  blue_comp_1?: number | null
  blue_comp_2?: number | null
  blue_comp_3?: number | null
  blue_comp_4?: number | null
  blue_comp_5?: number | null
  blue_comp_6?: number | null
  blue_comp_7?: number | null
  blue_comp_8?: number | null
  blue_comp_9?: number | null
  blue_comp_10?: number | null
  blue_comp_11?: number | null
  blue_comp_12?: number | null
  blue_comp_13?: number | null
  blue_comp_14?: number | null
  blue_comp_15?: number | null
  blue_comp_16?: number | null
  blue_comp_17?: number | null
  blue_comp_18?: number | null
}

/**
 * An enumeration for if the match has occurred or is upcomming.
 *
 * Members:
 * UPCOMING: Match has not yet occurred or data has not be fetched.
 * COMPLETED: Match has been completed and data has been uploaded.
 */
export type MatchStatus = "Upcoming" | "Completed"

/**
 * An enumeration for the type of match at the event.
 *
 * Members:
 * INVALID: The match is invalid for some reason.
 * QUAL: Qualification Match
 * EIGHTH: First round elimination match.
 * QUARTER: Second round or quarterfinal elimination match.
 * SEMI: Semifinal elimination match.
 * FINAL: Finals elimination match.
 */
export type MatchType = "invalid" | "qm" | "ef" | "qf" | "sf" | "f"

/**
 * An enumeration for which alliance won a match.
 *
 * Members:
 * RED: The red alliance won the match.
 * BLUE: The blue alliance won the match.
 * TIE: The match ended in a tie.
 */
export type MatchWinner = "red" | "blue" | "tie" | ""

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

export type SearchIndex = {
  events?: Array<EventSearch>
  teams?: Array<TeamSearch>
}

/**
 * An enumeration for US states and Canadian provinces.
 */
export type StateProv =
  | "Alabama"
  | "Alaska"
  | "American Samoa"
  | "Arizona"
  | "Arkansas"
  | "California"
  | "Colorado"
  | "Connecticut"
  | "Delaware"
  | "District of Columbia"
  | "Florida"
  | "Georgia"
  | "Guam"
  | "Hawaii"
  | "Idaho"
  | "Illinois"
  | "Indiana"
  | "Iowa"
  | "Kansas"
  | "Kentucky"
  | "Louisiana"
  | "Maine"
  | "Maryland"
  | "Massachusetts"
  | "Michigan"
  | "Minnesota"
  | "Mississippi"
  | "Missouri"
  | "Montana"
  | "Nebraska"
  | "Nevada"
  | "New Hampshire"
  | "New Jersey"
  | "New Mexico"
  | "New York"
  | "North Carolina"
  | "North Dakota"
  | "Northern Mariana Islands"
  | "Ohio"
  | "Oklahoma"
  | "Oregon"
  | "Pennsylvania"
  | "Puerto Rico"
  | "Rhode Island"
  | "South Carolina"
  | "South Dakota"
  | "Tennessee"
  | "Texas"
  | "Utah"
  | "Vermont"
  | "Virgin Islands"
  | "Virginia"
  | "Washington"
  | "West Virginia"
  | "Wisconsin"
  | "Wyoming"
  | "Newfoundland"
  | "Prince Edward Island"
  | "Nova Scotia"
  | "New Brunswick"
  | "Québec"
  | "Ontario"
  | "Manitoba"
  | "Saskatchewan"
  | "Alberta"
  | "British Columbia"
  | "Yukon"
  | "Northwest Territories"
  | "Nunavut"
  | ""

export type Team = {
  key: string
  number: number
  nickname: string
  rookie_year: number | null
  country: string | null
  state_prov: StateProv
  city: string | null
  district?: District
}

export type TeamSearch = {
  number: number
  nickname: string
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type EventEventData = {
  key: string
}

export type EventEventResponse = Event

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type TbaInitTeamsResponse = Message

export type TbaInitEventsData = {
  year: number
}

export type TbaInitEventsResponse = Message

export type TbaInitMatchesData = {
  year: number
}

export type TbaInitMatchesResponse = Message

export type TeamGetTeamByKeyData = {
  key: string
}

export type TeamGetTeamByKeyResponse = Team

export type TeamGetEventsByYearData = {
  key: string
  year: number
}

export type TeamGetEventsByYearResponse = Array<Event>

export type TeamGetMatchesByEventData = {
  eventKey: string
  teamKey: string
}

export type TeamGetMatchesByEventResponse = Array<Match>

export type TeamGetMatchesByYearData = {
  teamKey: string
  year: number
}

export type TeamGetMatchesByYearResponse = Array<Match>

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsSearchIndexResponse = SearchIndex

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
