"""adjusted match

Revision ID: 96939518c3cd
Revises: 3a8851a6d8e0
Create Date: 2025-07-09 20:47:48.384441

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '96939518c3cd'
down_revision = '3a8851a6d8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('match', sa.Column('red_tiebreaker', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('blue_tiebreaker', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'match', 'yearstats', ['year'], ['year'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column('match', 'blue_tiebreaker')
    op.drop_column('match', 'red_tiebreaker')
    op.drop_column('match', 'year')
    # ### end Alembic commands ###
