"""adjusted match winner to account for matches that haven't happened. not sure if this does anything

Revision ID: c4e4b56e5ca1
Revises: d38caa288575
Create Date: 2025-07-09 22:04:26.047377

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c4e4b56e5ca1'
down_revision = 'd38caa288575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
