"""adjust team name to team nickname

Revision ID: e7416ba0392c
Revises: 07b4badc747c
Create Date: 2025-07-20 12:02:45.769988

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e7416ba0392c'
down_revision = '07b4badc747c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'name', new_column_name='nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'nickname', new_column_name='name')
    # ### end Alembic commands ###
