"""add TeamEvent

Revision ID: fce7ed2fdcfe
Revises: e7416ba0392c
Create Date: 2025-07-23 20:36:44.263252

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fce7ed2fdcfe'
down_revision = 'e7416ba0392c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teamevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_key'], ['event.key'], ),
    sa.ForeignKeyConstraint(['team_key'], ['team.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teamevent')
    # ### end Alembic commands ###
